name: Build and Release Flatpak

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-x86_64:
    name: Build Flatpak (x86_64)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flatpak-node-generator
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install aiohttp toml
          python3 -m pip install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node

      - name: Generate generated-sources.json
        run: |
          python3 -m flatpak_node_generator npm package-lock.json -o generated-sources.json

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: iCloudMail-x86_64.flatpak
          manifest-path: moe.bdim.iCloudMail.json
          arch: x86_64
          cache: true
          repository-name: flathub
          repository-url: https://flathub.org/repo/flathub.flatpakrepo
          upload-artifact: false
        env:
          FLATPAK_BUILDER_ALLOW_MISSING_RUNTIMES: "1"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iCloudMail-flatpak-x86_64
          path: iCloudMail-x86_64.flatpak
          retention-days: 90

  build-aarch64:
    name: Build Flatpak (aarch64)
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flatpak-node-generator
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install aiohttp toml
          python3 -m pip install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node

      - name: Generate generated-sources.json
        run: |
          python3 -m flatpak_node_generator npm package-lock.json -o generated-sources.json

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: iCloudMail-aarch64.flatpak
          manifest-path: moe.bdim.iCloudMail.json
          arch: aarch64
          cache: true
          repository-name: flathub
          repository-url: https://flathub.org/repo/flathub.flatpakrepo
          upload-artifact: false
        env:
          FLATPAK_BUILDER_ALLOW_MISSING_RUNTIMES: "1"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iCloudMail-flatpak-aarch64
          path: iCloudMail-aarch64.flatpak
          retention-days: 90

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-x86_64, build-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.flatpak
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## iCloud Mail Flatpak Release

            Download the appropriate flatpak for your architecture:
            - `iCloudMail-x86_64.flatpak` - for Intel/AMD 64-bit systems
            - `iCloudMail-aarch64.flatpak` - for ARM64 systems

            ### Installation
            ```bash
            flatpak install --user iCloudMail-x86_64.flatpak
            ```

            ### Running
            ```bash
            flatpak run moe.bdim.iCloudMail
            ```
